### ISSUE TITLE
[Feature Request] 建议在 Flyout 弹出时，可以点击非 Flyout 区域来关闭 Flyout

### ISSUE THREAD

**Issue by h82258652** [MrZhangYuan/Unicorn.ViewManager#6]
建议添加这么一个 property，这样的话，在 app 设计时 flyout 内就不需要 close button 了，可以留出更大的空间。

**Comment by MrZhangYuan** [comment]
Flyout和Dialog都继承自PopupItem，这个父类有一个属性是IsEasyClose，默认值是False，作用就是点击灰色区域快速关闭，感谢

**Comment by h82258652** [comment]
@MrZhangYuan 谢谢回复，只试了下 demo，哈哈。建议 demo 详细一点。

**Comment by MrZhangYuan** [comment]
好的，后面会逐步细化Demo，谢谢关注
